### ISSUE TITLE
Error attempting to use VersionedManytoMany field

### ISSUE THREAD

**Issue by b-d-b** [swisscom/cleanerversion#52]
With the latest release of your nice plugin (which I am very grateful you have provided to the community), I encountered a problem using the VersionedManyToMany field.

My model setup is like so:

Cassette(Versionable):
{{details}}

CassetteGross(Versionable):
cassettes = VersionedManyToManyField(Cassette)

When I attempt to access the cassettes from my CassetteGross object (cg below), I get the following error:

>>> cg.cassettes.current.all()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\dev\pythonenv\LIS\lib\site-packages\django\db\models\query.py", line 116, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "C:\dev\pythonenv\LIS\lib\site-packages\django\db\models\query.py", line 141, in __iter__
    self._fetch_all()
  File "C:\dev\pythonenv\LIS\lib\site-packages\versions\models.py", line 375, in _fetch_all
    self._result_cache = list(self.iterator())
  File "C:\dev\pythonenv\LIS\lib\site-packages\django\db\models\query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "C:\dev\pythonenv\LIS\lib\site-packages\django\db\models\sql\compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "C:\dev\pythonenv\LIS\lib\site-packages\django\db\models\sql\compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "C:\dev\pythonenv\LIS\lib\site-packages\django\db\backends\utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\dev\pythonenv\LIS\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\dev\pythonenv\LIS\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\dev\pythonenv\LIS\lib\site-packages\django\utils\six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "C:\dev\pythonenv\LIS\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column case_cassettegross_cassettes.cassette_id does not exist
LINE 1: ...settegross_cassettes" ON ( "case_cassette"."id" = "case_cass..

I was wondering if you could give me some feedback as to whether this is a problem on my end of things so that I may go about fixing this.  I am also wondering if you could comment back with the release information for the new version if possible?

Thanks for your continued support, I hope I can help resolve this issue.

Regards,

Mike

**Comment by b-d-b** [comment]
If it helps, I get the same error attempting to go the other way with the relation, like:

cassette = Cassete.someobject
cassette.cassettegross_set.current.all()

Returns the same stacktrace.

Similarly, when attempting to add a cassette to the cassettegross I get the same stacktrace.

**Comment by maennel** [comment]
Hi @b-d-b 

Thanks for your feedback, glad you like CleanerVersion. 

What version did you work with previously? 
I know it's a bit hidden, but in the [Release Notes of version 1.4.0](https://github.com/swisscom/cleanerversion/releases/tag/v1.4.0) it says that the DB schema is changed from that version on. Concretely, this means that column names are forced to be lowercase in versions >= 1.4.0. So, if you set up your schema with a version <1.4.0 (where column names were CamelCase combined with underlines) this may be the error. 
Unfortunately, we didn't write any migrating script for this. 

Looking at your stacktrace, this may be the reason for the error you're getting. 
In order to be sure, it's not something else, try to run the unit tests that come with the CleanerVersion sources.
If you already are sure, do the following steps to resolve (assuming my guess was right):
- back up your DB
- change the column names to be lowercase (simply replacing uppercase letters by lowercase ones should do the trick)
- test

The easiest thing of course would be to throw away the current DB and to let Django create a new one. But this also means that your data will be gone. ;)

Looking forward to your feedback.
-Manuel

**Comment by brki** [comment]
@b-d-b : Does this work:?

```
cg = CassetteGross.objects.current.get(...)
cg.cassettes.all()
```

That should give you all the current cassettes associated with cg.  The current-ness should be propagated automatically.

Of course, maennel's previous comment may indeed be the cause of your problem.

**Comment by b-d-b** [comment]
Actually Manuel's idea seemed to work.  We dropped our database and reran the migrations and it fixed the problem.  Thanks for your quick feedback and support of the problem at hand.  If there is any way I can help support this project in the future, please let me know.  Great work guys.
