### ISSUE TITLE
Django Admin-integration: Add unicode support

### ISSUE THREAD

**Issue by maennel** [swisscom/cleanerversion#86]
Currently it does not seem to be possible to insert strings including unicode characters ("äöüé..."). Try to insert a city like "Zürich" to reproduce.

**Comment by boydjohnson** [comment]
This is caused by the __str__ method of the model. For the error I found it was City in the versions_tests.models file and the __str__ method is the function versionable_description. My understanding is that the unicode handling would be model specific depending on what language and words are being used in the model fields.

**Comment by boydjohnson** [comment]
In Python 2 you can use the \__unicode\__ method and prepend u'' to everything. Check out [django docs](https://docs.djangoproject.com/en/1.8/topics/python3/#string-handling) for reading on unicode handling in Python 2 and 3. You can use a class decorator python_2_unicode_compatible to make the \__str\__ into a \__unicode\__ in Python 2 and do nothing in Python 3, to make the code compatible with Python 2 and 3. I haven't gotten the decorator to work yet on the versions_tests code, but I did get it to work correctly in Python 2 by just renaming \__str\__ as \__unicode\__

**Comment by boydjohnson** [comment]
Got it to work with python_2_unicode_compatible decorator. So every versions_tests.models class with a __str__ method is both Python 2 and Python 3 unicode compatible.
